esphome:
  name: ck0 # This is the name of the node. It should always be unique in your ESPHome network. May only contain lowercase characters, digits and hyphens. It also gets prefixed to entity names.
  # if you change this name after already adding to HA - to make entities names all update - you need to delete the device in HA and then re-add it > device settigns 3 dots > recreate entitiy IDs - it should keep data
  friendly_name: CellKeeper0 # This name is sent to the frontend and used by Home Assistant as the integration and device name. It also gets prefixed to entity names when needed.
  min_version: 2025.11.0 
  project:
    name: "CellKeeper.ESP32-S3-Touch-LCD-7"
    version: "1.0b" 
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio
    build_flags: 
      - -DBOARD_HAS_PSRAM

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
#      CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_80M: y
#      CONFIG_SPIRAM_SPEED_120M: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_USE_MALLOC: y
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      #CONFIG_COMPILER_OPTIMIZATION_DEBUG: y
    advanced:
      loop_task_stack_size: 8704 #pr#10564
#      enable_idf_experimental_features: False
#      compiler_optimization: SIZE

# Modular Packages
packages:
  bms_core: !include bms_core.yaml
  bms_ui: !include bms_ui_scripts.yaml
  ui_layout: !include ui_800x480.yaml

psram:
  mode: octal
  speed: 80MHz

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

switch:
  - platform: template
    name: "Web Log Toggle"
    id: web_log_toggle
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  use_address: 10.60.11.225
  ap:
    ssid: "BMS-LCD-7-Hotspot"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    on_begin:
      then:
        - light.turn_off: display_backlight
        - lvgl.pause: {}

logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: DEBUG
  logs:
    web_server: ERROR # Default to only errors for the web server to save bandwidth
    hmi_bms: INFO
    sensor: WARN
    text_sensor: WARN
    number: WARN

uart:
  - id: uart_bus
    tx_pin: GPIO19
    rx_pin:
      number: GPIO20
      mode:
        input: true
        pullup: false
    baud_rate: 460800
    rx_buffer_size: 1024

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO09
    scan: true

ch422g:
  - id: ch422g_hub

output:
  - platform: gpio
    id: lcdbacklight_output
    pin:
      ch422g: ch422g_hub
      number: 2

light:
  - platform: binary
    output: lcdbacklight_output
    id: display_backlight
    name: LCD Backlight
    restore_mode: ALWAYS_ON

touchscreen:
  - platform: gt911
    id: my_touchscreen
    interrupt_pin: GPIO4
    reset_pin:
      ch422g: ch422g_hub
      number: 1
      mode: OUTPUT

display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB
    auto_clear_enabled: false
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      - GPIO14 # B3
      - GPIO38 # B4
      - GPIO18 # B5
      - GPIO17 # B6
      - GPIO10 # B7
      - GPIO39 # G2
      - GPIO0  # G3
      - GPIO45 # G4
      - GPIO48 # G5
      - GPIO47 # G6
      - GPIO21 # G7
      - GPIO1  # R3
      - GPIO2  # R4
      - GPIO42 # R5
      - GPIO41 # R6
      - GPIO40 # R7
